baseURL = 'https://mikeyguinness.com/'
locale = 'en-us'
title = 'Mikey Guinness'
theme = "mg-hugo-theme"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Projects"
  url = "/projects/"

[[params.navlinks]]
  name = "Blog"
  url = "/blog/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
